/*
 * Software Architecture Task 2
 *
 * Group 21
 *
 * Christian Tinauer
 * Marco Stranner
 * Mario Bacher
 * Matthias Tomaschek
 *
 */
package com.sat2client;

import javax.swing.*;


public class ClientGUI extends javax.swing.JFrame {
    
    private DefaultListModel stopsResultListModel;
    private DefaultListModel checkConnectionResultListModel;
    private DefaultListModel newLineStopsListModel;
    private String server_address = "http://127.0.0.1:3000";
    
    /**
     * Creates new form
     */
    public ClientGUI() {
        stopsResultListModel = new DefaultListModel();
        checkConnectionResultListModel = new DefaultListModel();
        newLineStopsListModel = new DefaultListModel();

        initComponents();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the look and feel */
        //<editor-fold defaultstate="collapsed" desc="Look and feel setting code">
        try {
            javax.swing.UIManager.setLookAndFeel(javax.swing.UIManager.getSystemLookAndFeelClassName());
            //javax.swing.UIManager.setLookAndFeel(javax.swing.UIManager.getCrossPlatformLookAndFeelClassName());
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClientGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClientGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClientGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClientGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ClientGUI().setVisible(true));
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabbedPane = new javax.swing.JTabbedPane();
        stopsPanel = new javax.swing.JPanel();
        nameLabel = new javax.swing.JLabel();
        nameTF = new javax.swing.JTextField();
        longitudeLabel = new javax.swing.JLabel();
        longitudeTF = new javax.swing.JTextField();
        longitudeComboBox = new javax.swing.JComboBox<>();
        latitudeLabel = new javax.swing.JLabel();
        latitudeTF = new javax.swing.JTextField();
        latitudeComboBox = new javax.swing.JComboBox<>();
        searchButton = new javax.swing.JButton();
        stopsResultListScrollPane = new javax.swing.JScrollPane();
        stopsResultList = new javax.swing.JList<>();
        addToConCheckLabel = new javax.swing.JLabel();
        addStop1Button = new javax.swing.JButton();
        addStop2Button = new javax.swing.JButton();
        addToLinesButton = new javax.swing.JButton();
        connectionsPanel = new javax.swing.JPanel();
        stop1Label = new javax.swing.JLabel();
        stop1NameTF = new javax.swing.JTextField();
        stop2Label = new javax.swing.JLabel();
        stop2NameTF = new javax.swing.JTextField();
        checkConnectionButton = new javax.swing.JButton();
        checkConnectionResultListScrollPane = new javax.swing.JScrollPane();
        checkConnectionResultList = new javax.swing.JList<>();
        jSeparator2 = new javax.swing.JSeparator();
        newLineStopsListScrollPane = new javax.swing.JScrollPane();
        newLineStopsList = new javax.swing.JList<>();
        moveUpButton = new javax.swing.JButton();
        moveDownButton = new javax.swing.JButton();
        newLineLabel = new javax.swing.JLabel();
        newLineNameTF = new javax.swing.JTextField();
        createLineButton = new javax.swing.JButton();
        newLineNameLabel = new javax.swing.JLabel();
        deleteStopButton = new javax.swing.JButton();
        clearStopsButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SA Task 2");
        setMinimumSize(new java.awt.Dimension(640, 480));
        setResizable(false);

        nameLabel.setText("Name or ID:");

        nameTF.setToolTipText("Name");

        longitudeLabel.setText("Longitude:");

        longitudeTF.setToolTipText("Longitude");

        longitudeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "above", "below" }));

        latitudeLabel.setText("Latitude:");

        latitudeTF.setToolTipText("Latitude");

        latitudeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "above", "below" }));

        searchButton.setText("Search");
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });

        stopsResultList.setModel(stopsResultListModel);
        stopsResultList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        stopsResultListScrollPane.setViewportView(stopsResultList);

        addToConCheckLabel.setText("Add selection to:");
        addToConCheckLabel.setToolTipText("");

        addStop1Button.setText("From");
        addStop1Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addStop1ButtonActionPerformed(evt);
            }
        });

        addStop2Button.setText("To");
        addStop2Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addStop2ButtonActionPerformed(evt);
            }
        });

        addToLinesButton.setText("New line");
        addToLinesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addToLinesButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout stopsPanelLayout = new javax.swing.GroupLayout(stopsPanel);
        stopsPanel.setLayout(stopsPanelLayout);
        stopsPanelLayout.setHorizontalGroup(
            stopsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(stopsPanelLayout.createSequentialGroup()
                .addGroup(stopsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(stopsResultListScrollPane, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(stopsPanelLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(stopsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(stopsPanelLayout.createSequentialGroup()
                                .addComponent(nameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(nameTF, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(stopsPanelLayout.createSequentialGroup()
                                .addComponent(longitudeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(longitudeTF, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(longitudeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(stopsPanelLayout.createSequentialGroup()
                                .addComponent(latitudeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(latitudeTF, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(latitudeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(16, 16, 16)
                                .addComponent(searchButton)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, stopsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(addToConCheckLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(addStop1Button)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addStop2Button)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addToLinesButton)
                .addGap(136, 136, 136))
        );
        stopsPanelLayout.setVerticalGroup(
            stopsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(stopsPanelLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(stopsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(stopsPanelLayout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(nameLabel))
                    .addComponent(nameTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(stopsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(stopsPanelLayout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(longitudeLabel))
                    .addComponent(longitudeTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(stopsPanelLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(longitudeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(6, 6, 6)
                .addGroup(stopsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(stopsPanelLayout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(latitudeLabel))
                    .addComponent(latitudeTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(stopsPanelLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(latitudeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(searchButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(stopsResultListScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 301, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(stopsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addToLinesButton)
                    .addComponent(addStop2Button)
                    .addComponent(addStop1Button)
                    .addComponent(addToConCheckLabel)))
        );

        tabbedPane.addTab("Stops", stopsPanel);

        stop1Label.setText("From:");

        stop2Label.setText("To:");

        checkConnectionButton.setText("Check");
        checkConnectionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkConnectionButtonActionPerformed(evt);
            }
        });

        checkConnectionResultList.setModel(checkConnectionResultListModel);
        checkConnectionResultListScrollPane.setViewportView(checkConnectionResultList);

        newLineStopsList.setModel(newLineStopsListModel);
        newLineStopsListScrollPane.setViewportView(newLineStopsList);

        moveUpButton.setText("Up");
        moveUpButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                moveUpButtonActionPerformed(evt);
            }
        });

        moveDownButton.setText("Down");
        moveDownButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                moveDownButtonActionPerformed(evt);
            }
        });

        newLineLabel.setText("Create new line:");

        createLineButton.setText("Create");
        createLineButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createLineButtonActionPerformed(evt);
            }
        });

        newLineNameLabel.setText("Name:");

        deleteStopButton.setText("Delete");
        deleteStopButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteStopButtonActionPerformed(evt);
            }
        });

        clearStopsButton.setText("Clear");
        clearStopsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearStopsButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout connectionsPanelLayout = new javax.swing.GroupLayout(connectionsPanel);
        connectionsPanel.setLayout(connectionsPanelLayout);
        connectionsPanelLayout.setHorizontalGroup(
            connectionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(connectionsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(connectionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(checkConnectionResultListScrollPane)
                    .addGroup(connectionsPanelLayout.createSequentialGroup()
                        .addComponent(stop1Label)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(stop1NameTF, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(stop2Label)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(stop2NameTF, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(checkConnectionButton))
                    .addGroup(connectionsPanelLayout.createSequentialGroup()
                        .addComponent(newLineLabel)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, connectionsPanelLayout.createSequentialGroup()
                        .addGroup(connectionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(connectionsPanelLayout.createSequentialGroup()
                                .addComponent(newLineStopsListScrollPane)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                            .addGroup(connectionsPanelLayout.createSequentialGroup()
                                .addComponent(newLineNameLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(newLineNameTF, javax.swing.GroupLayout.PREFERRED_SIZE, 465, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)))
                        .addGroup(connectionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(createLineButton, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                            .addComponent(clearStopsButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(moveUpButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(moveDownButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(deleteStopButton, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))))
                .addContainerGap())
        );
        connectionsPanelLayout.setVerticalGroup(
            connectionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(connectionsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(connectionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(stop1NameTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(checkConnectionButton)
                    .addComponent(stop2NameTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(stop2Label)
                    .addComponent(stop1Label))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(checkConnectionResultListScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(newLineLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(connectionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(connectionsPanelLayout.createSequentialGroup()
                        .addComponent(deleteStopButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(clearStopsButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(moveUpButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(moveDownButton))
                    .addComponent(newLineStopsListScrollPane, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addGroup(connectionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(createLineButton)
                    .addComponent(newLineNameTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(newLineNameLabel)))
        );

        tabbedPane.addTab("Connections", connectionsPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabbedPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabbedPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        tabbedPane.getAccessibleContext().setAccessibleName("Stops");

        pack();
    }// </editor-fold>//GEN-END:initComponents
                                       
    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed

        // Start a THREAD for this! No UI lockup! SwingWorker!

        String name = nameTF.getText();
        String longitude = longitudeTF.getText();
        String latitude = latitudeTF.getText();

        boolean useName = !name.isEmpty();
        boolean useLongitude = !longitude.isEmpty();
        boolean useLatitude = !latitude.isEmpty();

        // Get info from ComboBox
        boolean longitudeAbove = longitudeComboBox.getSelectedIndex() == 0;
        boolean latitudeAbove = latitudeComboBox.getSelectedIndex() == 0;

        SearchStopsWorker worker = new SearchStopsWorker(stopsResultListModel,
                                                         searchButton,
                                                         useName, name,
                                                         useLongitude, longitude,
                                                         longitudeAbove,
                                                         useLatitude, latitude,
                                                         latitudeAbove, server_address);
        worker.execute();

    }//GEN-LAST:event_searchButtonActionPerformed

    private void checkConnectionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkConnectionButtonActionPerformed

        String start_name = stop1NameTF.getText();
        String stop_name = stop2NameTF.getText();

        if((!start_name.isEmpty()) && (!stop_name.isEmpty())) {
            CheckConnectionsWorker worker = new CheckConnectionsWorker(checkConnectionResultListModel, checkConnectionButton, start_name, stop_name, server_address);
            worker.execute();
        } else {
            JOptionPane.showMessageDialog(null, "Stops \"From\" and \"To\" must not be empty!");
        }

    }//GEN-LAST:event_checkConnectionButtonActionPerformed

    private void addStop1ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addStop1ButtonActionPerformed

        if (!stopsResultListModel.isEmpty()) {
            PublicTransportStop selectedStop = stopsResultList.getSelectedValue();
            String selectedStopName = selectedStop.getName();
            stop1NameTF.setText(selectedStopName);
        }
        
    }//GEN-LAST:event_addStop1ButtonActionPerformed

    private void addStop2ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addStop2ButtonActionPerformed

        if (!stopsResultListModel.isEmpty()) {
            PublicTransportStop selectedStop = stopsResultList.getSelectedValue();
            String selectedStopName = selectedStop.getName();
            stop2NameTF.setText(selectedStopName);
        }
        
    }//GEN-LAST:event_addStop2ButtonActionPerformed

    private void addToLinesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addToLinesButtonActionPerformed
        
        PublicTransportStop selectedStop = stopsResultList.getSelectedValue();
        newLineStopsListModel.addElement(selectedStop);
        
    }//GEN-LAST:event_addToLinesButtonActionPerformed

    private void clearStopsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearStopsButtonActionPerformed

        newLineStopsListModel.clear();

    }//GEN-LAST:event_clearStopsButtonActionPerformed

    private void deleteStopButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteStopButtonActionPerformed

        if (!newLineStopsListModel.isEmpty()) {
            newLineStopsListModel.remove(newLineStopsList.getSelectedIndex());
        }

    }//GEN-LAST:event_deleteStopButtonActionPerformed

    private void moveUpButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_moveUpButtonActionPerformed
        
        int selectedIndex = newLineStopsList.getSelectedIndex();
        
        // Perform only if an item is selected, and if it is not the topmost item
        if(selectedIndex > 0) {
            PublicTransportStop stopAbove = (PublicTransportStop) newLineStopsListModel.get(selectedIndex - 1);
            PublicTransportStop stopSelected = (PublicTransportStop) newLineStopsListModel.get(selectedIndex);
            
            newLineStopsListModel.set(selectedIndex, stopAbove);
            newLineStopsListModel.set(selectedIndex - 1, stopSelected);
            
            newLineStopsList.setSelectedIndex(selectedIndex - 1);
        }
        
    }//GEN-LAST:event_moveUpButtonActionPerformed

    private void moveDownButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_moveDownButtonActionPerformed
        
        int selectedIndex = newLineStopsList.getSelectedIndex();
        
        // Perform only if an item is selected, and if it is not the last item
        if((selectedIndex > -1) && (selectedIndex < (newLineStopsListModel.getSize() - 1))) {
            PublicTransportStop stopBelow = (PublicTransportStop)newLineStopsListModel.get(selectedIndex + 1);
            PublicTransportStop stopSelected = (PublicTransportStop)newLineStopsListModel.get(selectedIndex);
            
            newLineStopsListModel.set(selectedIndex, stopBelow);
            newLineStopsListModel.set(selectedIndex + 1, stopSelected);
            
            newLineStopsList.setSelectedIndex(selectedIndex + 1);
        }
        
    }//GEN-LAST:event_moveDownButtonActionPerformed

    private void createLineButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createLineButtonActionPerformed

        String newLineName = newLineNameTF.getText();

        if(newLineName.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Name must not be empty!");
        } else if(newLineStopsListModel.getSize() < 2) {
            JOptionPane.showMessageDialog(null, "Line must contain two or more stops!");
        } else {
            AddLineWorker worker = new AddLineWorker(newLineStopsListModel,
                                                     createLineButton,
                                                     newLineName,
                                                     server_address);
            worker.execute();
        }
        
    }//GEN-LAST:event_createLineButtonActionPerformed
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addStop1Button;
    private javax.swing.JButton addStop2Button;
    private javax.swing.JLabel addToConCheckLabel;
    private javax.swing.JButton addToLinesButton;
    private javax.swing.JButton checkConnectionButton;
    private javax.swing.JList<Route> checkConnectionResultList;
    private javax.swing.JScrollPane checkConnectionResultListScrollPane;
    private javax.swing.JButton clearStopsButton;
    private javax.swing.JPanel connectionsPanel;
    private javax.swing.JButton createLineButton;
    private javax.swing.JButton deleteStopButton;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JComboBox<String> latitudeComboBox;
    private javax.swing.JLabel latitudeLabel;
    private javax.swing.JTextField latitudeTF;
    private javax.swing.JComboBox<String> longitudeComboBox;
    private javax.swing.JLabel longitudeLabel;
    private javax.swing.JTextField longitudeTF;
    private javax.swing.JButton moveDownButton;
    private javax.swing.JButton moveUpButton;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JTextField nameTF;
    private javax.swing.JLabel newLineLabel;
    private javax.swing.JLabel newLineNameLabel;
    private javax.swing.JTextField newLineNameTF;
    private javax.swing.JList<PublicTransportStop> newLineStopsList;
    private javax.swing.JScrollPane newLineStopsListScrollPane;
    private javax.swing.JButton searchButton;
    private javax.swing.JLabel stop1Label;
    private javax.swing.JTextField stop1NameTF;
    private javax.swing.JLabel stop2Label;
    private javax.swing.JTextField stop2NameTF;
    private javax.swing.JPanel stopsPanel;
    private javax.swing.JList<PublicTransportStop> stopsResultList;
    private javax.swing.JScrollPane stopsResultListScrollPane;
    private javax.swing.JTabbedPane tabbedPane;
    // End of variables declaration//GEN-END:variables
}
